backend:
  name: github
  repo: bishalnepali/rejango
  branch: main # or the name of your default branch

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "Hello World"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Author
        name: author
        widget: string
      - label: Body
        name: body
        widget: markdown
